import type { SignerJob } from '../entities/signer-job.entity';
import type { SignerResult } from '../contracts/signer-result.contract';
import type { SignerPayload } from '../contracts/signer-payload.contract';
import type { SignerJobType } from '../enums/signer-job-type.enum';

/**
 * Input contract for `ISignerJobService.createJob()`.
 *
 * The caller (WalletModule / SweepModule / WithdrawalModule) must supply
 * a fully sealed `SignerPayload` produced by `SigningPayloadBuilder`.
 * The service only persists — it never constructs or inspects the payload.
 */
export interface CreateJobParams {
  /** Business-origin classifier. Internal only — never sent to the Signer. */
  readonly jobType: SignerJobType;
  /** UUID of the network on which this job operates. */
  readonly networkId: string;
  /** UUID of the wallet entity. Denormalised from payload.walletId. */
  readonly walletId: string;
  /** UUID of the originating business entity (wallet / sweep / withdrawal). */
  readonly referenceId: string;
  /** Discriminator for referenceId. Values: 'wallet' | 'sweep' | 'withdrawal'. */
  readonly referenceType: string;
  /**
   * The fully sealed, integrity-signed SignerPayload produced by SigningPayloadBuilder.
   * The service stores this verbatim. It never reads or modifies its contents.
   */
  readonly payload: SignerPayload;
}

/**
 * Input contract for `ISignerJobService.claimJob()`.
 */
export interface ClaimJobParams {
  /** UUID of the SignerJob row to claim. */
  readonly jobId: string;
  /** Stable identifier of the Signer instance performing the claim. */
  readonly signerInstanceId: string;
  /** One-time nonce generated by the service and issued to the Signer. */
  readonly claimToken: string;
}

/**
 * Input contract for `ISignerJobService.completeJob()`.
 */
export interface CompleteJobParams {
  /** UUID of the SignerJob row to complete. */
  readonly jobId: string;
  /** The claim token previously issued to the Signer at claim time. */
  readonly claimToken: string;
  /** The validated SignerResult returned by the Offline Signer. */
  readonly result: SignerResult;
}

/**
 * Input contract for `ISignerJobService.markFailed()`.
 */
export interface MarkFailedParams {
  /** UUID of the SignerJob row to mark as failed. */
  readonly jobId: string;
  /** Human-readable reason for the failure. Stored in errorMessage column. */
  readonly reason: string;
}

/**
 * Business logic contract for the SignerJob lifecycle.
 *
 * This interface defines the complete public API of `SignerJobService`.
 * Every method either returns a fully populated `SignerJob` entity or
 * a primitive aggregate value.
 *
 * Rules (enforced by architecture review — Phase 3.5 Revision 3)
 * --------------------------------------------------------------
 * - All state-mutating methods throw typed domain errors on invalid transitions.
 * - Methods never return null.
 * - Methods never throw generic `Error`.
 * - No method communicates with the Offline Signer, RPC nodes, or queues.
 * - No method calls a BlockchainDriver.
 * - No method performs cryptographic operations.
 */
export interface ISignerJobService {
  /**
   * Creates an immutable SignerJob row from a sealed SignerPayload.
   *
   * Post-conditions:
   * - status = PENDING
   * - retryCount = 0
   * - payload column sealed; all immutable fields set
   *
   * @throws {SignerJobNotFoundError} — never (create always succeeds or throws a generic persistence error).
   */
  createJob(params: CreateJobParams): Promise<SignerJob>;

  /**
   * Returns a SignerJob by UUID.
   * @throws {SignerJobNotFoundError} When the row does not exist.
   */
  findById(id: string): Promise<SignerJob>;

  /**
   * Returns a SignerJob by its requestId.
   * @throws {SignerJobNotFoundError} When no row matches the requestId.
   */
  findByRequestId(requestId: string): Promise<SignerJob>;

  /**
   * Transitions a PENDING job to CLAIMED.
   *
   * @throws {SignerJobNotFoundError}       When the job does not exist.
   * @throws {SignerJobExpiredError}         When expiresAt < now.
   * @throws {SignerJobAlreadyClaimedError}  When status is already CLAIMED.
   * @throws {SignerJobInvalidStatusError}   When status is not PENDING.
   */
  claimJob(params: ClaimJobParams): Promise<SignerJob>;

  /**
   * Transitions a CLAIMED job to COMPLETED and stores the SignerResult.
   *
   * @throws {SignerJobNotFoundError}      When the job does not exist.
   * @throws {SignerJobCompletedError}     When the job is already COMPLETED.
   * @throws {SignerJobInvalidStatusError} When status is not CLAIMED.
   */
  completeJob(params: CompleteJobParams): Promise<SignerJob>;

  /**
   * Transitions a PENDING or CLAIMED job to CANCELLED.
   *
   * Only jobs that have not yet reached a terminal state may be cancelled.
   *
   * @throws {SignerJobNotFoundError}      When the job does not exist.
   * @throws {SignerJobCompletedError}     When the job is already COMPLETED.
   * @throws {SignerJobInvalidStatusError} When the job is in FAILED or EXPIRED.
   */
  cancelJob(jobId: string): Promise<SignerJob>;

  /**
   * Transitions a PENDING or CLAIMED job to EXPIRED.
   *
   * Called by the scheduled expiry cron task. Verifies that expiresAt has
   * actually passed before applying the transition.
   *
   * @throws {SignerJobNotFoundError}      When the job does not exist.
   * @throws {SignerJobCompletedError}     When the job is already in a terminal state.
   * @throws {SignerJobInvalidStatusError} When the transition is not permitted.
   */
  expireJob(jobId: string): Promise<SignerJob>;

  /**
   * Increments `retryCount` by 1.
   *
   * The caller (expiry cron) is responsible for deciding whether to
   * re-queue or permanently expire the job after incrementing.
   *
   * @throws {SignerJobNotFoundError} When the job does not exist.
   * @throws {SignerJobInvalidStatusError} When retryCount would exceed maxRetries.
   */
  incrementRetry(jobId: string): Promise<SignerJob>;

  /**
   * Transitions a CLAIMED job to FAILED and records the failure reason.
   *
   * @throws {SignerJobNotFoundError}      When the job does not exist.
   * @throws {SignerJobInvalidStatusError} When status is not CLAIMED.
   */
  markFailed(params: MarkFailedParams): Promise<SignerJob>;

  /**
   * Returns `true` when a non-deleted job with the given UUID exists.
   * Never throws.
   */
  exists(jobId: string): Promise<boolean>;

  /**
   * Returns the count of jobs currently in PENDING status.
   * Used by monitoring and the admin dashboard.
   */
  countPending(): Promise<number>;

  /**
   * Returns the count of jobs currently in CLAIMED status.
   * Used by monitoring and the admin dashboard.
   */
  countClaimed(): Promise<number>;
}
