import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
} from 'typeorm';
import { SignerJobStatus } from '../enums/signer-job-status.enum';
import { SignerJobType } from '../enums/signer-job-type.enum';
import type { SignerPayload } from '../contracts/signer-payload.contract';
import type { SignerResult } from '../contracts/signer-result.contract';

/**
 * Persistent record of a single cryptographic signing request issued to
 * the Offline Signer.
 *
 * Each row represents one unit of work: a fully-prepared, integrity-signed
 * `SignerPayload` waiting to be claimed, signed offline, and submitted back.
 *
 * Design invariants (see Phase 3.5 Architecture — Revision 3):
 *
 * IMMUTABLE after creation (never change post-insert):
 *   jobType, requestId, networkId, payloadVersion, protocolVersion,
 *   payload (entire JSONB column), expiresAt, referenceId, referenceType.
 *
 * MUTABLE (only these fields may change after insert):
 *   status, claimedBy, claimedAt, claimToken, completedAt,
 *   retryCount, result, errorMessage, updatedAt, version.
 *
 * Hard deletion is permanently forbidden (ADR-JM-006).
 * Use TypeORM `softRemove()` only — but in practice signer jobs are
 * never soft-deleted either; soft-delete exists as a safety mechanism only.
 *
 * Optimistic locking via `@VersionColumn` prevents lost-update races
 * when concurrent processes (cron + submit) touch the same row.
 */
@Entity('signer_jobs')
@Index('IDX_signer_jobs_status', ['status'])
@Index('IDX_signer_jobs_status_expires', ['status', 'expiresAt'])
@Index('IDX_signer_jobs_reference', ['referenceType', 'referenceId'])
@Index('IDX_signer_jobs_request_id', ['requestId'], { unique: true })
export class SignerJob {
  /**
   * Universally unique row identifier.
   * UUID v4, generated by the database. Never expose sequential integers.
   */
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  /**
   * UUID v4 generated by `SigningPayloadBuilder`.
   * Mirrors `payload.requestId` at the column level for fast indexed lookups
   * without parsing the JSONB payload column.
   *
   * Unique constraint enforces one-to-one mapping between a requestId
   * and a signer_jobs row, preventing duplicate job creation.
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'uuid', name: 'request_id' })
  public requestId!: string;

  /**
   * UUID of the wallet entity referenced in the payload.
   * Denormalised from `payload.walletId` for indexed lookups.
   * Not a foreign key — the wallet entity lives in WalletModule (Phase 4).
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'uuid', name: 'wallet_id' })
  @Index('IDX_signer_jobs_wallet_id')
  public walletId!: string;

  /**
   * UUID of the network on which this job operates.
   * Used by `SignerJobRepository.findAvailable()` to filter by network.
   * Not a foreign key at this layer — NetworkModule owns that constraint.
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'uuid', name: 'network_id' })
  @Index('IDX_signer_jobs_network_id')
  public networkId!: string;

  /**
   * Business-origin classifier. Internal audit use only.
   * THE OFFLINE SIGNER NEVER RECEIVES THIS VALUE.
   *
   * IMMUTABLE after creation.
   */
  @Column({
    type: 'enum',
    enum: SignerJobType,
    name: 'job_type',
  })
  public jobType!: SignerJobType;

  /**
   * Current lifecycle state. The only field mutated during normal job flow.
   * See `SignerJobStatus` for the full state machine.
   */
  @Column({
    type: 'enum',
    enum: SignerJobStatus,
    default: SignerJobStatus.PENDING,
  })
  public status!: SignerJobStatus;

  /**
   * Schema version of the `SignerPayload` struct stored in `payload`.
   * Denormalised for fast version checks without JSONB parsing.
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'smallint', name: 'payload_version' })
  public payloadVersion!: number;

  /**
   * Backend–Signer protocol version in effect when this job was created.
   * Denormalised for observability and compatibility checks.
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'smallint', name: 'protocol_version' })
  public protocolVersion!: number;

  /**
   * The complete, sealed `SignerPayload` object.
   *
   * Contains ALL information the Offline Signer requires:
   * signingPayload, payloadDigest, integritySignature, versions,
   * walletId, network, signAlgorithm, signatureFormat, and timestamps.
   *
   * THE JOB MANAGER NEVER PARSES OR MODIFIES THIS COLUMN AFTER CREATION.
   * Served verbatim to the Signer via the polling endpoint.
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'jsonb' })
  public payload!: SignerPayload;

  /**
   * Deadline timestamp, denormalised from `payload.expiresAt` for
   * efficient indexed cron queries (no JSONB parsing needed).
   *
   * The scheduled expiry task queries:
   *   WHERE status = 'CLAIMED' AND expires_at < NOW()
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'timestamptz', name: 'expires_at' })
  public expiresAt!: Date;

  /**
   * Stable identifier of the originating business entity.
   * Combined with `referenceType` for unambiguous cross-module lookup.
   *
   * Examples: wallet.id, withdrawal.id, sweep.id
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'uuid', name: 'reference_id' })
  public referenceId!: string;

  /**
   * Discriminator for `referenceId`. Identifies which module owns the
   * referenced entity.
   *
   * Values: 'wallet' | 'sweep' | 'withdrawal'
   *
   * IMMUTABLE after creation.
   */
  @Column({ type: 'varchar', length: 50, name: 'reference_type' })
  public referenceType!: string;

  // ---------------------------------------------------------------------------
  // Signer interaction — MUTABLE
  // ---------------------------------------------------------------------------

  /**
   * Stable identifier of the Signer instance that claimed this job.
   * NULL until claimed. Set by `SignerJobService.claimJob()`.
   * Used to detect and reject duplicate claims from different instances.
   */
  @Column({ type: 'varchar', length: 255, name: 'claimed_by', nullable: true })
  public claimedBy!: string | null;

  /**
   * Timestamp when the Signer claimed this job.
   * NULL until claimed.
   */
  @Column({ type: 'timestamptz', name: 'claimed_at', nullable: true })
  public claimedAt!: Date | null;

  /**
   * One-time nonce issued at claim time (ADR-JM-003).
   * The Signer must include this verbatim in the submit request.
   * Backend rejects submissions where this does not match.
   * NULL until claimed.
   */
  @Column({ type: 'uuid', name: 'claim_token', nullable: true })
  public claimToken!: string | null;

  /**
   * Timestamp when the job reached a terminal state
   * (COMPLETED, FAILED, or EXPIRED).
   * NULL until terminal.
   */
  @Column({ type: 'timestamptz', name: 'completed_at', nullable: true })
  public completedAt!: Date | null;

  /**
   * Number of times this job has been re-queued after expiry.
   * Default 0. Incremented by the expiry task when `retryCount < maxRetries`.
   * When `retryCount >= maxRetries` the job transitions to EXPIRED instead.
   * See Extension Point §9.3 in the architecture document.
   */
  @Column({ type: 'smallint', name: 'retry_count', default: 0 })
  public retryCount!: number;

  // ---------------------------------------------------------------------------
  // Result — MUTABLE, immutable after first write
  // ---------------------------------------------------------------------------

  /**
   * The complete `SignerResult` returned by the Offline Signer.
   * NULL until COMPLETED. Written once; never modified after.
   *
   * Contains: requestId, signature, publicKey, signAlgorithm,
   * signatureFormat, signerVersion, signedAt, executionTimeMs.
   */
  @Column({ type: 'jsonb', nullable: true })
  public result!: SignerResult | null;

  /**
   * Human-readable error description.
   * Set when status transitions to FAILED or EXPIRED.
   * NULL for COMPLETED jobs.
   */
  @Column({ type: 'text', name: 'error_message', nullable: true })
  public errorMessage!: string | null;

  // ---------------------------------------------------------------------------
  // Audit — automatic
  // ---------------------------------------------------------------------------

  /**
   * Optimistic locking version counter.
   * Automatically incremented by TypeORM on every `save()`.
   * Prevents lost-update races between concurrent cron and submit operations.
   */
  @VersionColumn()
  public version!: number;

  /** Row creation timestamp. Set once by TypeORM. Immutable. */
  @CreateDateColumn({ name: 'created_at' })
  public createdAt!: Date;

  /** Last mutation timestamp. Automatically updated by TypeORM. */
  @UpdateDateColumn({ name: 'updated_at' })
  public updatedAt!: Date;

  /**
   * Soft-delete timestamp. NULL for active records.
   * Hard deletion is permanently forbidden (ADR-JM-006).
   * TypeORM appends `WHERE deleted_at IS NULL` to all queries automatically.
   */
  @DeleteDateColumn({ name: 'deleted_at', nullable: true })
  public deletedAt!: Date | null;
}
