import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
} from 'typeorm';
import { NetworkDriver } from '../enums/network-driver.enum';

/**
 * Represents one supported blockchain network.
 *
 * This is the **dependency root** for every other business entity in the
 * platform. All chain-aware modules (Token, Wallet, Deposit, Withdrawal,
 * Sweep, Broadcast) carry a foreign key to this table.
 *
 * Design invariants:
 * - Records are NEVER hard-deleted. Use TypeORM `softRemove()` only.
 * - `slug` and `chainId` are immutable after creation (see ADR-N-013).
 * - `driverKey` stores a `NetworkDriver` enum value; the Drivers layer maps
 *   this to a concrete implementation class at runtime.
 * - No RPC endpoints, secrets, or blockchain SDK references are stored here.
 *
 * Optimistic locking via `@VersionColumn` prevents lost-update races when
 * two operators concurrently modify the same network record.
 */
@Entity('networks')
export class Network {
  /**
   * Universally unique identifier.
   * UUID v4, generated by the database. Never expose sequential integers
   * for resource IDs — they leak cardinality and enable enumeration attacks.
   */
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  /**
   * Human-readable display name.
   * Must be unique across all networks.
   * Example: 'Ethereum', 'Tron', 'BNB Smart Chain'
   */
  @Column({ type: 'varchar', length: 100, unique: true })
  public name!: string;

  /**
   * URL-safe unique identifier. Used as a stable external reference key
   * in logs, configuration files, and API responses.
   * Example: 'ethereum-mainnet', 'tron-mainnet', 'bsc-mainnet'
   *
   * IMMUTABLE after creation — changing it breaks external references
   * in configuration files, monitoring dashboards, and partner integrations.
   * A database migration with an ADR is required to rename a slug.
   */
  @Column({ type: 'varchar', length: 100, unique: true })
  public slug!: string;

  /**
   * Native currency ticker symbol.
   * Used in API responses, fee displays, and amount formatting.
   * Example: 'ETH', 'TRX', 'BNB'
   */
  @Column({ type: 'varchar', length: 20 })
  public symbol!: string;

  /**
   * Chain-level network identifier.
   * - EVM chains: EIP-155 chain ID as a decimal string (e.g. '1' for Ethereum mainnet)
   * - Tron: canonical network name string (e.g. 'tron-mainnet')
   * - Other chains: network-specific genesis identifier
   *
   * Stored as VARCHAR to accommodate non-integer identifiers.
   * IMMUTABLE after creation — changing it requires a migration + ADR.
   * Unique constraint prevents accidental duplicate network registrations.
   */
  @Column({ type: 'varchar', length: 100, unique: true, name: 'chain_id' })
  public chainId!: string;

  /**
   * Decimal precision of the native currency.
   * Used by amount formatters to convert raw integer amounts to human-readable
   * decimal strings without floating-point precision loss.
   * Example: 18 for ETH (Wei), 6 for TRX (SUN)
   */
  @Column({ type: 'smallint', name: 'native_decimals' })
  public nativeDecimals!: number;

  /**
   * Driver family identifier.
   * Stored as a VARCHAR enum value. The Drivers layer maps this string to a
   * concrete driver class at runtime — Network never references driver code.
   *
   * Example: NetworkDriver.EVM → 'evm' → EvmDriver class (in Drivers layer)
   *
   * Never a relational foreign key — drivers are code artefacts, not rows.
   */
  @Column({
    type: 'enum',
    enum: NetworkDriver,
    name: 'driver_key',
  })
  public driverKey!: NetworkDriver;

  /**
   * Block explorer base URL.
   * Used to construct transaction hash and address links for the API.
   * Trailing slash is normalised away by `NetworkService.getExplorerUrl()`.
   * Example: 'https://etherscan.io', 'https://tronscan.org'
   */
  @Column({ type: 'varchar', length: 255, name: 'explorer_base_url' })
  public explorerBaseUrl!: string;

  /**
   * Minimum number of block confirmations required before a deposit is
   * considered irreversible and credited to the user's balance.
   * Read by the Deposit Scanner module.
   * Conservative defaults: 12 for EVM (approximately 2.4 minutes), 20 for Tron.
   */
  @Column({ type: 'smallint', name: 'required_confirmations', default: 12 })
  public requiredConfirmations!: number;

  /**
   * Approximate average block time in seconds.
   * Informational only — used in API responses to estimate confirmation wait
   * times. Must NOT be used for timing logic or sleep intervals in code.
   * Example: 12 for Ethereum, 3 for Tron, 3 for BSC
   */
  @Column({ type: 'smallint', name: 'block_time_seconds', default: 12 })
  public blockTimeSeconds!: number;

  /**
   * Testnet flag.
   * True for non-production networks (Goerli, Sepolia, Nile, Shasta, etc.).
   * Allows the application to apply relaxed validation rules or skip
   * certain safety checks in non-production environments.
   */
  @Column({ type: 'boolean', name: 'is_testnet', default: false })
  public isTestnet!: boolean;

  /**
   * Activation gate.
   * When false, every downstream module (Wallet, Deposit, Withdrawal, Sweep)
   * must reject operations on this network before performing any on-chain action.
   * Deactivating a network is a safe, non-destructive operation — no cascade.
   */
  @Column({ type: 'boolean', name: 'is_active', default: true })
  public isActive!: boolean;

  /**
   * Optional human-readable description.
   * Intended for operator documentation, not for runtime logic.
   */
  @Column({ type: 'text', nullable: true })
  public description!: string | null;

  /**
   * Optimistic locking version counter.
   * Automatically incremented by TypeORM on every `save()` call.
   * Prevents lost-update race conditions when two processes concurrently
   * modify the same network record.
   */
  @VersionColumn()
  public version!: number;

  /** Record creation timestamp. Set once by TypeORM; never manually modified. */
  @CreateDateColumn({ name: 'created_at' })
  public createdAt!: Date;

  /** Last update timestamp. Automatically updated by TypeORM on every save. */
  @UpdateDateColumn({ name: 'updated_at' })
  public updatedAt!: Date;

  /**
   * Soft-delete timestamp.
   * NULL for active records. Set by TypeORM `softRemove()` — never set manually.
   * TypeORM's `@DeleteDateColumn` automatically appends `WHERE deleted_at IS NULL`
   * to all queries, making soft-deleted records invisible to normal queries.
   */
  @DeleteDateColumn({ name: 'deleted_at', nullable: true })
  public deletedAt!: Date | null;
}
