import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
  JoinColumn,
} from 'typeorm';
import { Network } from '@modules/network/entities/network.entity';
import { TokenType } from '../enums/token-type.enum';
import { TokenStatus } from '../enums/token-status.enum';
import { TokenStandard } from '../enums/token-standard.enum';

/**
 * Represents a blockchain asset supported by the platform.
 *
 * Covers both native coins (ETH, TRX, BNB) and smart-contract tokens
 * (ERC-20, TRC-20, BEP-20).
 *
 * Design invariants (enforced at entity + service level)
 * -------------------------------------------------------
 * - `networkId`, `type`, `standard`, `contractAddress`, and `decimals` are
 *   IMMUTABLE after creation. Changing any of these fields requires a
 *   soft-delete of the old record and registration of a new one.
 * - Exactly ONE native token may exist per network (partial unique index).
 * - `contractAddress` is NULL for native tokens and non-null for contract
 *   tokens. Empty strings and the zero address are rejected by the service.
 * - Records are NEVER hard-deleted. Use TypeORM `softRemove()` only.
 * - `(networkId, symbol)` is unique among live records (partial unique index).
 * - `(networkId, contractAddress)` is unique among live contract tokens
 *   (partial unique index).
 * - Optimistic locking via `@VersionColumn` prevents lost-update races.
 */
@Entity('tokens')
@Index('idx_tokens_network_id', ['networkId'])
@Index('idx_tokens_status', ['status'])
@Index('idx_tokens_type', ['type'])
@Index('idx_tokens_standard', ['standard'])
export class Token {
  /**
   * UUID v4 primary key — generated by the database.
   * Never expose sequential integers: UUIDs prevent enumeration attacks.
   */
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  /**
   * Foreign key to the `networks` table.
   *
   * IMMUTABLE after creation (Invariant 10).
   * ON DELETE RESTRICT — soft-deleting a network must not cascade to tokens.
   * Indexed for the dominant query pattern: "all tokens for network X".
   */
  @Column({ type: 'uuid', name: 'network_id' })
  public networkId!: string;

  @ManyToOne(() => Network, { onDelete: 'RESTRICT', nullable: false, eager: false })
  @JoinColumn({ name: 'network_id' })
  public network!: Network;

  /**
   * Discriminator: native coin vs smart-contract token.
   *
   * IMMUTABLE after creation (Invariant 11).
   * Stored as a Postgres ENUM column.
   */
  @Column({ type: 'enum', enum: TokenType })
  public type!: TokenType;

  /**
   * Token protocol standard.
   *
   * IMMUTABLE after creation.
   * Drives amount-encoding and ABI-decoding in the Drivers layer.
   * Stored as a Postgres ENUM column.
   */
  @Column({ type: 'enum', enum: TokenStandard })
  public standard!: TokenStandard;

  /**
   * Human-readable display name.
   * Mutable — assets occasionally rebrand.
   * Example: 'Ether', 'Tether USD', 'BNB'
   */
  @Column({ type: 'varchar', length: 100 })
  public name!: string;

  /**
   * Ticker symbol.
   * Mutable — rebrands may change the symbol.
   * Unique per network among live records (partial unique index).
   * Example: 'ETH', 'USDT', 'BNB'
   */
  @Column({ type: 'varchar', length: 20 })
  public symbol!: string;

  /**
   * Decimal precision of the asset's smallest unit.
   *
   * IMMUTABLE after creation (Invariant 8).
   * Changing decimals after tokens are in circulation causes catastrophic
   * mis-calculation of every historical deposit and withdrawal amount.
   * Range: 0–36. Common values: 18 (ETH/BNB), 6 (USDT/TRX).
   */
  @Column({ type: 'smallint' })
  public decimals!: number;

  /**
   * On-chain smart-contract address.
   *
   * IMMUTABLE after creation (Invariant 9).
   * NULL for native tokens — the only valid "absent" representation.
   * Empty string and zero address are rejected by the service layer.
   * EVM format:  0x-prefixed 40 hex chars (20 bytes).
   * Tron format: Base58Check starting with 'T' (34 chars).
   */
  @Column({ type: 'varchar', length: 100, name: 'contract_address', nullable: true })
  public contractAddress!: string | null;

  /**
   * Lifecycle state of the token.
   *
   * Mutable — with transition restrictions enforced by the service.
   * DEPRECATED is a terminal state (irreversible).
   */
  @Column({ type: 'enum', enum: TokenStatus, default: TokenStatus.ACTIVE })
  public status!: TokenStatus;

  /**
   * Per-token override for the number of block confirmations required
   * before a deposit is considered final.
   *
   * Mutable. NULL means "use the network default" (Invariant 15).
   * Range when non-null: 1–500.
   */
  @Column({ type: 'smallint', name: 'confirmations_override', nullable: true })
  public confirmationsOverride!: number | null;

  /**
   * HTTPS URL pointing to the token's logo image.
   * Mutable — presentation metadata only (Invariant 14).
   * NULL when no logo has been provided.
   */
  @Column({ type: 'varchar', length: 512, name: 'logo_url', nullable: true })
  public logoUrl!: string | null;

  /**
   * Optional operator description.
   * Mutable — informational only. Must never contain business logic.
   */
  @Column({ type: 'text', nullable: true })
  public description!: string | null;

  /**
   * Optimistic locking version counter.
   * Auto-incremented by TypeORM on every `save()` call.
   * Prevents lost-update races when two processes concurrently modify the
   * same token record. Never exposed in API responses.
   */
  @VersionColumn()
  public version!: number;

  /** Record creation timestamp. Set once by TypeORM; never manually modified. */
  @CreateDateColumn({ name: 'created_at' })
  public createdAt!: Date;

  /** Last update timestamp. Automatically refreshed by TypeORM on every save. */
  @UpdateDateColumn({ name: 'updated_at' })
  public updatedAt!: Date;

  /**
   * Soft-delete timestamp.
   * NULL for live records. Set by TypeORM `softRemove()` — never set manually.
   * TypeORM automatically appends `WHERE deleted_at IS NULL` to all queries,
   * making soft-deleted records invisible to normal operations.
   */
  @DeleteDateColumn({ name: 'deleted_at', nullable: true })
  public deletedAt!: Date | null;
}
