import type { SignAlgorithm } from '../enums/sign-algorithm.enum';
import type { SignatureFormat } from '../enums/signature-format.enum';

/**
 * Network context embedded inside a SignerPayload.
 *
 * Contains the minimum network information the Offline Signer needs to
 * select the correct curve and serialisation. No business data is included.
 * The Signer uses `driverKey` to resolve curve parameters; `chainId` and
 * `nativeSymbol` are informational only.
 */
export interface SignerPayloadNetwork {
  /** Canonical chain identifier (e.g. '1' for Ethereum mainnet, 'tron-mainnet'). */
  readonly chainId: string;
  /** Driver family key: 'evm' | 'tron'. Determines curve and tx format. */
  readonly driverKey: string;
  /** Native currency symbol for logging only. No Signer logic depends on it. */
  readonly nativeSymbol: string;
}

/**
 * Versioned, integrity-signed cryptographic contract delivered to the
 * Offline Signer.
 *
 * This is the ONLY payload the Signer ever receives. It is constructed
 * exclusively by `SigningPayloadBuilder` and is immutable after creation.
 *
 * The Job Manager treats `signingPayload` as an opaque blob — it stores
 * and transfers it without parsing, modifying, or interpreting its contents.
 *
 * Field immutability: once this object is serialised into the `payload`
 * JSONB column of a `signer_jobs` row, no field may change.
 * See Architecture Rule §10, items 10–16.
 *
 * The Signer MUST:
 * 1. Verify `integritySignature` before any other operation.
 * 2. Verify `payloadVersion` is understood.
 * 3. Verify `expiresAt` has not passed.
 * 4. Recompute `payloadDigest` from `signingPayload` and verify it matches.
 * 5. Sign `signingPayload` bytes using `signAlgorithm`.
 * 6. Return a `SignerResult` in the format specified by `signatureFormat`.
 */
export interface SignerPayload {
  // — Versioning —

  /**
   * Schema version of this `SignerPayload` structure.
   * Current value: 1.
   * The Signer rejects payloads with an unknown `payloadVersion`.
   * Increment this when the shape of `SignerPayload` changes.
   */
  readonly payloadVersion: number;

  /**
   * Backend–Signer communication protocol version.
   * Current value: 1.
   * Independent of `payloadVersion`; governs transport-level semantics.
   */
  readonly protocolVersion: number;

  /**
   * Encoding version of the `signingPayload` bytes.
   * Specific to the driver family (e.g. EIP-2718 envelope version for EVM).
   * Current value: 1.
   * The Signer uses this to understand the byte structure if needed.
   */
  readonly transactionVersion: number;

  // — Request Identity —

  /**
   * UUID v4 generated by `SigningPayloadBuilder`.
   * Binds this payload to exactly one `signer_jobs` row.
   * The Signer MUST echo this value verbatim in `SignerResult.requestId`.
   * The backend rejects any result where `requestId` does not match.
   */
  readonly requestId: string;

  // — Wallet Reference —

  /**
   * UUID of the wallet entity whose private key must be used for signing.
   * Opaque to the Signer — used solely as a key selector to locate the
   * correct private key in secure storage.
   * No business meaning is conveyed by this value.
   */
  readonly walletId: string;

  // — Network Context —

  /** Minimum network metadata required by the Signer. See SignerPayloadNetwork. */
  readonly network: SignerPayloadNetwork;

  // — Signing Parameters —

  /**
   * Cryptographic algorithm the Signer must use.
   * Determines both the signing curve and the `payloadDigest` function.
   * The Signer MUST echo this in `SignerResult.signAlgorithm`.
   */
  readonly signAlgorithm: SignAlgorithm;

  /**
   * Required encoding format of the returned signature.
   * The Signer MUST produce a signature in exactly this format.
   * The backend rejects results where `signatureFormat` does not match.
   */
  readonly signatureFormat: SignatureFormat;

  // — Opaque Signing Payload —

  /**
   * Hex-encoded canonical byte payload produced by `BlockchainDriver.buildTransaction()`.
   *
   * The Signer applies its private key to these bytes using `signAlgorithm`.
   *
   * THE JOB MANAGER TREATS THIS AS AN OPAQUE BLOB.
   * It never parses, interprets, or modifies the contents.
   * Different driver families produce different byte formats
   * (RLP for EVM, Protobuf for Tron) without changing this field.
   *
   * Determinism guarantee: given identical input parameters,
   * `BlockchainDriver.buildTransaction()` MUST always produce identical bytes
   * (Architecture Rule §9 / ADR-JM-013).
   */
  readonly signingPayload: string;

  // — Digest —

  /**
   * Hex-encoded deterministic cryptographic digest of `signingPayload` bytes.
   *
   * Computed by `SigningPayloadBuilder` using the digest function implied
   * by `signAlgorithm` (keccak256 for ECDSA_SECP256K1, SHA-512 for ED25519,
   * SHA-256d for SCHNORR).
   *
   * The Signer MUST recompute this digest from `signingPayload` and verify
   * it matches before performing any signing operation.
   * The backend also verifies this after receiving the `SignerResult`.
   *
   * NEVER assumes Ethereum keccak256 specifically — algorithm is
   * determined by `signAlgorithm` (ADR-JM-011).
   */
  readonly payloadDigest: string;

  // — Integrity —

  /**
   * HMAC-SHA256 of the canonical JSON serialisation of this payload,
   * excluding the `integritySignature` field itself.
   *
   * Generated by `IntegritySignatureService` as the FINAL step of
   * `SigningPayloadBuilder.build()`. The shared symmetric secret is held
   * exclusively by the backend configuration layer.
   *
   * The Signer MUST verify this before touching any private key material.
   * No signing operation may proceed if verification fails.
   */
  readonly integritySignature: string;

  // — Temporal Validity —

  /** ISO 8601 UTC timestamp of when `SigningPayloadBuilder` assembled this payload. */
  readonly createdAt: string;

  /**
   * ISO 8601 UTC deadline.
   * The Signer MUST reject payloads where `expiresAt` has passed.
   * The backend expiry cron also uses this value (denormalised to the entity).
   */
  readonly expiresAt: string;
}
